version: '2'
services:
  mongo:
    container_name: webmongo
    image: mongo
    volumes: 
        - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: webnode
    restart: always
    build: .
    ports:
      - '3000:8000'
    depends_on: 
        - mongo
  